# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
config:
  # Allow long lines (docs often have URLs, badges, etc.)
  MD013: false
  # Allow duplicate headings in different files/contexts
  MD024:
    siblings_only: true
  # Allow inline HTML (badges, details/summary, etc.)
  MD033: false
  # Allow bare URLs
  MD034: false
